package com.cqupt.domain;

import com.cqupt.common.BaseEntity;
// Generated 2015-12-16 11:15:13 by Hibernate Tools 4.3.1.Final

/**
 * Areacate generated by hbm2java
 */
public class Areacate extends BaseEntity {

	private Integer areacateid;
	private Integer pid;
	private String area;


	public Integer getAreacateid() {
		return areacateid;
	}

	public void setAreacateid(Integer areacateid) {
		this.areacateid = areacateid;
	}

	public Integer getPid() {
		return pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

}
