package com.cqupt.domain;
// Generated 2015-12-16 11:15:13 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.cqupt.common.BaseEntity;

/**
 * Shop generated by hbm2java
 */
public class Shop extends BaseEntity {

	private Integer shopid;
	private Shopcategory shopcategory;
	private String shoploginname;
	private String password;
	private String shopname;
	private String shopaddress;
	private String tel;
	private int sort;
	private int rank;
	private String introduc;
	private String photo;
	private int state;
	private Date createtime;
	private Set shopreplays = new HashSet(0);
	private Set goodses = new HashSet(0);
	
	/*
	 * @description: 新增字段
	 * @author: lsx
	 * @date: 2015/12/25
	 * 
	 */
	
	/** 总销量 */
	private int salenum;
	
	/** 配送价 */
	private double sendprice;
	
	/** 配送时间 */
	private String sendtime;
	
	/** 运营状态 */
	private int runstate;
	

	public Integer getShopid() {
		return shopid;
	}

	public void setShopid(Integer shopid) {
		this.shopid = shopid;
	}

	public Shopcategory getShopcategory() {
		return this.shopcategory;
	}

	public void setShopcategory(Shopcategory shopcategory) {
		this.shopcategory = shopcategory;
	}

	public String getShoploginname() {
		return this.shoploginname;
	}

	public void setShoploginname(String shoploginname) {
		this.shoploginname = shoploginname;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getShopname() {
		return this.shopname;
	}

	public void setShopname(String shopname) {
		this.shopname = shopname;
	}

	public String getShopaddress() {
		return this.shopaddress;
	}

	public void setShopaddress(String shopaddress) {
		this.shopaddress = shopaddress;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public int getSort() {
		return this.sort;
	}

	public void setSort(int sort) {
		this.sort = sort;
	}

	public int getRank() {
		return this.rank;
	}

	public void setRank(int rank) {
		this.rank = rank;
	}

	public String getIntroduc() {
		return this.introduc;
	}

	public void setIntroduc(String introduc) {
		this.introduc = introduc;
	}

	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Set getShopreplays() {
		return this.shopreplays;
	}

	public void setShopreplays(Set shopreplays) {
		this.shopreplays = shopreplays;
	}

	public Set getGoodses() {
		return this.goodses;
	}

	public void setGoodses(Set goodses) {
		this.goodses = goodses;
	}

	public int getSalenum() {
		return salenum;
	}

	public void setSalenum(int salenum) {
		this.salenum = salenum;
	}

	public double getSendprice() {
		return sendprice;
	}

	public void setSendprice(double sendprice) {
		this.sendprice = sendprice;
	}

	public String getSendtime() {
		return sendtime;
	}

	public void setSendtime(String sendtime) {
		this.sendtime = sendtime;
	}

	public int getRunstate() {
		return runstate;
	}

	public void setRunstate(int runstate) {
		this.runstate = runstate;
	}

}
