package com.cqupt.domain;
// Generated 2015-12-16 11:15:13 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import com.cqupt.common.BaseEntity;

/**
 * Shopcategory generated by hbm2java
 */
public class Shopcategory extends BaseEntity {

	private Integer shopcategoryid;
	private int pid;
	private String category;
	private Set shops = new HashSet(0);

	public Integer getShopcategoryid() {
		return shopcategoryid;
	}

	public void setShopcategoryid(Integer shopcategoryid) {
		this.shopcategoryid = shopcategoryid;
	}

	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public Set getShops() {
		return this.shops;
	}

	public void setShops(Set shops) {
		this.shops = shops;
	}

}
