package com.cqupt.domain;
// Generated 2015-12-16 11:15:13 by Hibernate Tools 4.3.1.Final

import java.util.Date;

import com.cqupt.common.BaseEntity;

/**
 * Shoppingcart generated by hbm2java
 */
public class Shoppingcart extends BaseEntity {

	private Integer shoppingcartid;
	private Goods goods;
	private User user;
	private int goodsnum;
	private Date createtime;

	public Integer getShoppingcartid() {
		return shoppingcartid;
	}

	public void setShoppingcartid(Integer shoppingcartid) {
		this.shoppingcartid = shoppingcartid;
	}

	public Goods getGoods() {
		return this.goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public int getGoodsnum() {
		return this.goodsnum;
	}

	public void setGoodsnum(int goodsnum) {
		this.goodsnum = goodsnum;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

}
