package com.cqupt.domain;

import com.cqupt.common.BaseEntity;
// Generated 2015-12-16 11:15:13 by Hibernate Tools 4.3.1.Final

/**
 * Admin generated by hbm2java
 */
public class Admin extends BaseEntity {

	private Integer adminid;
	private String username;
	private String password;


	public Integer getAdminid() {
		return adminid;
	}

	public void setAdminid(Integer adminid) {
		this.adminid = adminid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
