package com.cqupt.domain;

import com.cqupt.common.BaseEntity;
// Generated 2015-12-16 11:15:13 by Hibernate Tools 4.3.1.Final

/**
 * Orderdetail generated by hbm2java
 */
public class Orderdetail extends BaseEntity {

	private Integer orderdetailid;
	private Goods goods;
	private Order order;
	private String goodsname;
	private String goodsphoto;
	private int state;
	private double price;
	private int num;
	private double totalprice;


	public Integer getOrderdetailid() {
		return orderdetailid;
	}

	public void setOrderdetailid(Integer orderdetailid) {
		this.orderdetailid = orderdetailid;
	}

	public Goods getGoods() {
		return this.goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}

	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	public String getGoodsname() {
		return this.goodsname;
	}

	public void setGoodsname(String goodsname) {
		this.goodsname = goodsname;
	}

	public String getGoodsphoto() {
		return this.goodsphoto;
	}

	public void setGoodsphoto(String goodsphoto) {
		this.goodsphoto = goodsphoto;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public int getNum() {
		return this.num;
	}

	public void setNum(int num) {
		this.num = num;
	}

	public double getTotalprice() {
		return this.totalprice;
	}

	public void setTotalprice(double totalprice) {
		this.totalprice = totalprice;
	}

}
