package com.cqupt.domain;

import com.cqupt.common.BaseEntity;
// Generated 2015-12-16 11:15:13 by Hibernate Tools 4.3.1.Final

/**
 * Goodscategory generated by hbm2java
 */
public class Goodscategory extends BaseEntity {

	private Integer goodscategoryid;
	private int pid;
	private String category;


	public Integer getGoodscategoryid() {
		return goodscategoryid;
	}

	public void setGoodscategoryid(Integer goodscategoryid) {
		this.goodscategoryid = goodscategoryid;
	}

	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

}
