package com.cqupt.domain;
// Generated 2015-12-16 11:15:13 by Hibernate Tools 4.3.1.Final

import java.util.Date;

import com.cqupt.common.BaseEntity;

/**
 * Shopreplay generated by hbm2java
 */
public class Shopreplay extends BaseEntity {

	private int shopreplayid;
	private Shop shop;
	private User user;
	private String content;
	private Date createtime;
	private int state;

	public int getShopreplayid() {
		return shopreplayid;
	}

	public void setShopreplayid(int shopreplayid) {
		this.shopreplayid = shopreplayid;
	}

	public Shop getShop() {
		return this.shop;
	}

	public void setShop(Shop shop) {
		this.shop = shop;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

}
